# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b1c14a3f17747c4707e82415436d1eec6f63b6f0986123acaa7d77fdc61329cb77f456adb0b8c78d04368555911ebdee513a3ac6853297905c11bdae9ecea56

test:
  secret_key_base: fe345cdc55e67e4b45820b37a0c81f5e548e15a59dba3c53bb629cd75dd15958d8a94584e61c43cfa46f292e40b2f2bce46ce97163a268b1873cf503b191c5e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
